### ISSUE TITLE
Document 3rd party ETH1 client options

### ISSUE THREAD

**Issue by danbryan** [eth2-educators/eth-docker#102]
Add additional documentation to show how to use 3rd party ETH1 clients like infura

**Comment by yorickdowne** [comment]
Is what we have at https://eth2-docker.net/docs/Usage/ClientSetup good enough? It links to Nimbus docs for Infura, and to the Alchemy main site for Alchemy.

**Comment by yorickdowne** [comment]
I think what we have works
