### ISSUE TITLE
Setup CI/CD

### ISSUE THREAD

**Issue by danbryan** [eth2-educators/eth-docker#115]
Consider using something like travis or github actions to perform CI/CD
linting
shellcheck
formating
Changelog maybe

**Comment by mfiumara** [comment]
What would be the preferred CI / CD provider?

**Comment by yorickdowne** [comment]
I'm honestly not even sure what my options are :)

**Comment by mfiumara** [comment]
Action or travis as proposed could work, but if someone is getting paid for this project (by the Ethereum Foundation) I am not sure we can go the travis route (https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works).

**Comment by yorickdowne** [comment]
It looks like Github Actions is the way to go, and there's a project to make travis-style yml files work: https://github.com/marketplace/actions/run-travis-yml
