### ISSUE TITLE
Docker and Timezone

### ISSUE THREAD

**Issue by gwenvador** [eth2-educators/eth-docker#153]
Can we add a timezone setting in the .env so to have the time of the docker logs in sync with the local time? Or should it be configured in another way?

**Comment by yorickdowne** [comment]
Hmm. Could be done and would need to be tested. https://serverfault.com/questions/683605/docker-container-time-timezone-will-not-reflect-changes shows some ideas as to how.

UTC timestamps is a well-know *ix-ism for logs, and doesn't require knowing which TZ a machine was set to at build time. There is value in that, as well.

This isn't a priority for me, and, if you'd like to scratch that itch and offer a PR that defaults to UTC but can be changed to a user's TZ, that'd definitely be welcome.

**Comment by yorickdowne** [comment]
This has been implemented. Go ahead and test please, and let us know if you find issues.
