### ISSUE TITLE
Why are releases not tagged?

### ISSUE THREAD

**Issue by ardevd** [eth2-educators/eth-docker#240]
I might be missing something currently, but the documentation points to a [changelog](https://eth2-docker.net/docs/About/Changelog) but this GitHub repo has no release tags. Where do these releases come from and how do I obtain them?

**Comment by yorickdowne** [comment]
I don't have CI/CD set up to do releases. That's a definite drawback, I hear you. Let me see how to get more professional around that.

Right now you get a new version of the tool with a simple `git pull`, and if the way `.env` works changed, you'll want to recreate it from `default.env`

**Comment by mfiumara** [comment]
I feel like some migration scripts for the `.env` are also required, since I feel there's a lot of changes for every release. Maybe we can move this discussion to #115? I would gladly help with CI/CD.

**Comment by yorickdowne** [comment]
I'll get started on the migration. I agree it's needed at this point.

I'll happily take your help with CI/CD.

**Comment by ardevd** [comment]
> Right now you get a new version of the tool with a simple `git pull`, and if the way `.env` works changed, you'll want to recreate it from `default.env`

I don't think considering each commit to master (now renamed to `main` for some reason) as a new version makes much sense. 

You could also tag releases without the need for CI/CD. Just marking a specific commit as "this is version x.y.z" along with associated changelog and upgrade notes would go a long way.

I'm quite experienced with GitLab based CI/CD, so if you need any help I might be able to pitch in despite the different platform.

**Comment by yorickdowne** [comment]
"Just marking a specific commit as "this is version x.y.z" along with associated changelog and upgrade notes would go a long way."

That's low-key in. There is a version at the bottom of README.md, and there is a changelog on eth-docker.net.

**Comment by yorickdowne** [comment]
`.env` migration is in, it's now part of `./ethd update`

**Comment by yorickdowne** [comment]
> I'm quite experienced with GitLab based CI/CD, so if you need any help I might be able to pitch in despite the different platform.

I'll take the help, I have no experience. Even a simple link to a doc that explains "this is how you indicate something should be tagged and do that automatically with a changelog" would be excellent.

**Comment by yorickdowne** [comment]
Manually tagging for now. Everything else can be discussed in CI/CD issue. Thank you for this!
