### ISSUE TITLE
Dashboards - Lighthouse not working

### ISSUE THREAD

**Issue by crymo99** [eth2-educators/eth-docker#257]
Today I  made update to LH 1.4 && latest eth-docker v1.3.3.

Noticed that grafana LH dashboards are not working for me.

I'm using following env config:

COMPOSE_FILE=lh-base.yml:lh-grafana.yml:grafana-insecure.yml:lh-stats.yml

===

I tried to troubleshoot a bit, but not an expert.

Found out that prometheus config file is refering to "beacon"

$ docker exec -it bc335197963b /bin/sh
/prometheus $ vi /etc/prometheus/prometheus.yml

...
scrape_configs:
  - job_name: 'nodes'
    static_configs:
      - targets: ['beacon:5054']
....

**beacon** is not reachable from container.

I think this needs to be changed to new naming **consensus**

**Comment by yorickdowne** [comment]
Thank you for the PR to fix this!
