### ISSUE TITLE
eth-docker_consensus_1 exited with code 1

### ISSUE THREAD

**Issue by gh-user-source** [eth2-educators/eth-docker#259]
consensus_1         | SoftMaxHeapSize must be less than or equal to the maximum heap size
consensus_1         | Error: Could not create the Java Virtual Machine.
consensus_1         | Error: A fatal exception has occurred. Program will exit.
eth-docker_consensus_1 exited with code 1

I get this running Teku on Ubuntu 20.04 when viewing logs by typing ./ethd logs -f consensus

**Comment by yorickdowne** [comment]
This sounds like you ran on a machine with very little RAM. The max heap size is 25% of the available RAM, on an 8 GiB machine it'd be 2 GiB, which is also what soft max is set to.

You can run Teku on a machine with 8 GiB; if you also want an execution client, make that 16 GiB.

Running with 4 GiB is possible with Lighthouse or Nimbus.

**Comment by yorickdowne** [comment]
Unexpectedly, 2G soft max refuses to run on an 8 GiB machine. Lowered it to 1 GiB, and now it runs with 8 GiB total. Try again and thank you for the report!
