### ISSUE TITLE
ethd update wrong?

### ISSUE THREAD

**Issue by mfiumara** [eth2-educators/eth-docker#269]
Hey I'm trying to run `ethd update`, but this calls the environment migrate function after building the docker containers, which means they get built with the old environment. Shouldn't this be reversed?

**Comment by yorickdowne** [comment]
The changed environment variables (ETH1 to EC, BN to CC) are used when starting the containers, not when building them. The same is true for environment variables that may get added to `default.env`, such as the recent `BEACON_STATS_MACHINE`.

The order is deliberate: If a user has changed values for targets, or a source build, this will build as expected for them, even as those settings are, also deliberately, not migrated.

The reasons build targets aren't migrated are:
- It's a niche setting that most users do not touch
- The default may change, and it's friendlier to bring users along to the new default and require power users to put their changes in again; than to leave the bulk of users on old build targets that might stop client updates for them


Thanks for the question!

**Comment by yorickdowne** [comment]
Upon further thought, you are right. It is better to migrate first, then update clients. This is a bit inconvenient for people who change build targets, but that's a very niche use. It makes sure regular users get the "right" target.

Change made, and thank you for the issue!
