### ISSUE TITLE
Default Geth Dashboard in Grafana not getting data

### ISSUE THREAD

**Issue by currentoor** [eth2-educators/eth-docker#288]
First off, thank you for putting this wonderful repo together. It's made my life so much easier.

I chose to run an ETH1 geth node locally rather than use a 3rd party service. When I view the execution process logs via `sudo docker-compose logs execution` I see the following, which makes me think the ETH1 node is running correctly.

```
execution_1               | INFO [09-05|14:30:35.378] Unindexed transactions                   blocks=1  txs=0   tail=3,095,402 elapsed="177.801µs"
execution_1               | INFO [09-05|14:30:36.233] Imported new chain segment               blocks=1  txs=10  mgas=4.678  elapsed=12.415ms    mgasps=376.754  number=5,445,401 hash=5297ad..8aec40 dirty=59.91MiB
execution_1               | INFO [09-05|14:30:50.083] Imported new chain segment               blocks=1  txs=0   mgas=0.000  elapsed=2.039ms     mgasps=0.000    number=5,445,402 hash=ed6698..035aef dirty=59.75MiB
execution_1               | INFO [09-05|14:30:50.083] Unindexed transactions                   blocks=1  txs=0   tail=3,095,403 elapsed="79.741µs"
execution_1               | INFO [09-05|14:30:50.419] Imported new chain segment               blocks=1  txs=1   mgas=0.078  elapsed=1.798ms     mgasps=43.521   number=5,445,402 hash=976236..7377c8 dirty=59.76MiB
execution_1               | INFO [09-05|14:30:50.449] Deep froze chain segment                 blocks=4  elapsed=16.234ms    number=5,355,402 hash=f7e665..51cbbc
execution_1               | INFO [09-05|14:31:04.492] Chain reorg detected                     number=5,445,401 hash=d8bc37..21a1c6 drop=1 dropfrom=ed6698..035aef add=2 addfrom=dd0ced..78b218
execution_1               | INFO [09-05|14:31:04.493] Imported new chain segment               blocks=1  txs=18  mgas=6.759  elapsed=72.852ms    mgasps=92.780   number=5,445,403 hash=dd0ced..78b218 dirty=59.90MiB
```

But the included `geth_dashboard` in Grafana always says no data.

<img width="1792" alt="Screen Shot 2021-09-05 at 11 00 23 AM" src="https://user-images.githubusercontent.com/2679997/132136808-1119b88b-c8b4-49b5-9e4a-9db8939c1b2c.png">

Whereas the `prysm_ynager` dashboard does show some metrics. My deposit is still being processed by the prater beacon chain so maybe that's why I only see some data.

<img width="1792" alt="Screen Shot 2021-09-05 at 11 01 42 AM" src="https://user-images.githubusercontent.com/2679997/132136872-83ec9bba-55a1-489c-b9f7-0749ca6c6144.png">

Is one of my assumptions incorrect? Should this dashboard even be populated? How can I verify Geth is running correctly?

**Comment by yorickdowne** [comment]
Closing for now, please comment if this issue persists after adding `geth-grafana.yml`.
